---
- name: install bosh dependencies
  apt:
    name:
      - build-essential
      - zlib1g-dev
      - ruby
      - ruby-dev
      - openssl
      - libxslt1-dev 
      - libxml2-dev 
      - libssl-dev 
      - libreadline-dev
      - libyaml-dev 
      - libsqlite3-dev
      - sqlite3
  ignore_errors: yes

- name: install bosh cli
  include_role:
    name: github-release
  vars:
    repository: "{{bosh_cli.repository}}"
    release_asset_filter: "{{bosh_cli.release_asset_filter}}"
    archive_format: "{{bosh_cli.archive_format}}"
    binary_name: "{{bosh_cli.binary_name}}"
